import os

SAMPLES,FRAC = glob_wildcards(r"nanopore_assemblies/{sample}_{frac,\d{2}}.fasta")
SAMPLES = list(set(SAMPLES))
FRAC = list(set(FRAC))
print(SAMPLES)
print(FRAC)

PAIRED = ["1", "2"]

rule all:
        input:
                expand(r"pypolca/{sample}_{frac}.polypolish.pypolca.fasta", sample = SAMPLES, frac=FRAC)

rule fastp:
        input:
                "fastqs/{sample}_{paired}.fastq.gz"
        output:
                processed="fastp/{sample}_{paired}.fastq.gz",
                unpaired="fastp/{sample}_u{paired}.fastq.gz"
        params:
                name="{sample}"
        resources:
                mem_mb=lambda wildcards, attempt: attempt * 2000,
                time=lambda wildcards, attempt: attempt * 30
        conda:
                "conda_envs/fastp.yml"
        shell:
                """
                mkdir -p fastp/
                fastp --in1 fastqs/{params.name}_1.fastq.gz --in2 fastqs/{params.name}_2.fastq.gz --out1 fastp/{params.name}_1.fastq.gz --out2 fastp/{params.name}_2.fastq.gz --unpaired1 fastp/{params.name}_u1.fastq.gz --unpaired2 fastp/{params.name}_u2.fastq.gz
                """

rule bwa_index:
	input:
		r"nanopore_assemblies/{sample}_{frac,\d{2}}.fasta"
	output:
		multiext(r"nanopore_assemblies/{sample}_{frac,\d{2}}.fasta", ".0123", ".amb", ".ann", ".bwt.2bit.64", ".pac")
	conda:
		"conda_envs/bwa-mem2.yml"
	shell:
		"""
		bwa-mem2 index {input}
		"""


rule bwa:
	input:
		assembly=r"nanopore_assemblies/{sample}_{frac,\d{2}}.fasta",
		idx=multiext(r"nanopore_assemblies/{sample}_{frac,\d{2}}.fasta", ".0123", ".amb", ".ann", ".bwt.2bit.64", ".pac"),	
		reads="fastp/{sample}_{paired}.fastq.gz"
	output:
		r"polypolish/{sample}_{frac,\d{2}}/alignments_{sample}_{frac}_{paired}.sam"
	params:
		outfile=r"polypolish/{sample}_{frac,\d{2}}/alignments_{sample}_{frac}_{paired}.sam"
	resources:
		mem_mb=lambda wildcards, attempt: attempt * 2000,
		time=lambda wildcards, attempt: attempt * 35
	conda:
		"conda_envs/bwa-mem2.yml"
	shell:
		"""
		mkdir -p polypolish/
		bwa-mem2 mem -t 16 -a {input.assembly} {input.reads} > {params.outfile}
		"""

rule polypolish_insert_filter:
	input:
		align1=r"polypolish/{sample}_{frac,\d{2}}/alignments_{sample}_{frac}_1.sam",
		align2=r"polypolish/{sample}_{frac,\d{2}}/alignments_{sample}_{frac}_2.sam"
	output:
		filter1=r"polypolish/{sample}_{frac,\d{2}}/filtered_alignments_{sample}_{frac}_1.sam",
		filter2=r"polypolish/{sample}_{frac,\d{2}}/filtered_alignments_{sample}_{frac}_2.sam"
	resources:
		mem_mb=lambda wildcards, attempt: attempt * 2000,
		time=lambda wildcards, attempt: attempt * 30
	conda:
		"conda_envs/polypolish.yml"
	shell:
		"""
		polypolish filter --in1 {input.align1} --in2 {input.align2} --out1 {output.filter1} --out2 {output.filter2}
		"""

rule polypolish:
	input:
		assembly=r"nanopore_assemblies/{sample}_{frac,\d{2}}.fasta",
		filter1=r"polypolish/{sample}_{frac,\d{2}}/filtered_alignments_{sample}_{frac}_1.sam",
		filter2=r"polypolish/{sample}_{frac,\d{2}}/filtered_alignments_{sample}_{frac}_2.sam"
	output:
		r"polypolish/{sample}_{frac,\d{2}}/{sample}_{frac}.polypolish.fasta"
	resources:
		mem_mb=lambda wildcards, attempt: attempt * 2000,
		time=lambda wildcards, attempt: attempt * 30
	conda:
		"conda_envs/polypolish.yml"
	shell:
		"""
		polypolish polish {input.assembly} {input.filter1} {input.filter2} > {output}
		"""

rule pypolca:
	input:
		assembly=r"polypolish/{sample}_{frac,\d{2}}/{sample}_{frac}.polypolish.fasta",
		reads1="fastp/{sample}_1.fastq.gz",
		reads2="fastp/{sample}_2.fastq.gz"
	output:
		fa=r"pypolca/{sample}_{frac,\d{2}}.polypolish.pypolca.fasta"
	threads: 16
	resources:
		mem_mb=lambda wildcards, attempt: attempt * 4000,
		cpus=16
	conda:
		"conda_envs/pypolca.yml"
	params:
		out_path=r"pypolca_tmp/{sample}_{frac,\d{2}}"
	shell:
		"""
        pypolca run -a {input.assembly} -1 {input.reads1} -2 {input.reads2} -t {threads} -o {params.out_path} -f --careful
        mkdir -p pypolca
        cp {params.out_path}/pypolca_corrected.fasta {output.fa}
		"""

